Fix test failure, failed to convert CalendarLiteral to Date
Error message:

FAIL Converting from Clojure data structures to/from RDF - CalendarImpl to java.util.Date at (values.clj:42)
Expected:
Actual:
java.lang.IllegalArgumentException: No matching field found: calendarValue for class com.stardog.stark.impl.CalendarLiteral
  stardog.values$eval23218$fn__23219.invoke(values.clj:34)
  stardog.values$eval23453$fn__23454.invoke(values.clj:142)
  stardog.values$eval23432$fn__23433$G__23423__23438.invoke(values.clj:132)
  stardog.test.values$eval23731$fn__23732$fn__23733$fn__23776$fn__23777$fn__23778.invoke(values.clj:42)
  stardog.test.values$eval23731$fn__23732$fn__23733$fn__23776$fn__23777.invoke(values.clj:25)
  stardog.test.values$eval23731$fn__23732$fn__23733$fn__23776.invoke(values.clj:25)
  stardog.test.values$eval23731$fn__23732$fn__23733.invoke(values.clj:25)
  stardog.test.values$eval23731$fn__23732.invoke(values.clj:25)
  stardog.test.values$eval23731.invokeStatic(values.clj:25)
  stardog.test.values$eval23731.invoke(values.clj:25)
  stardog.test.core$eval23184.invokeStatic(form-init17478546949547615212.clj:128)
  stardog.test.core$eval23184.invoke(form-init17478546949547615212.clj:128)